In [28]:
import requests
import pandas as pd
from pandas import json_normalize

In [31]:
def fetch_tertiary_education_data(country_code='CO'):
    """
    Fetch tertiary (higher) education enrollment rate data for a given country using the World Bank API.
    
    Args:
    - country_code (str): ISO 2-character country code, default is 'CO' for Colombia.
    
    Returns:
    - DataFrame: Pandas DataFrame containing the response data.
    """
    url = f"http://api.worldbank.org/v2/country/{country_code}/indicator/SE.TER.ENRR?format=json&per_page=500"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()[1]  # The actual data is in the second element of the response list
        # Normalizar columnas 'indicator' y 'country' del JSON
        df = json_normalize(data)
        # Si necesitas renombrar las columnas para que tengan nombres más amigables, puedes hacerlo aquí
        # Ejemplo: df.rename(columns={'indicator.value': 'Indicator', 'country.value': 'Country'}, inplace=True)
        return df
    else:
        print(f"Error fetching data: {response.status_code}")
        return None

# Fetch data and print the DataFrame
df = fetch_tertiary_education_data()
if df is not None:
    print(df.head())  # Mostrar las primeras filas del DataFrame para revisión
else:
    print("No se pudo obtener los datos.")

  countryiso3code  date      value unit obs_status  decimal indicator.id  \
0             COL  2022        NaN                        0  SE.TER.ENRR
1             COL  2021  58.315922                        0  SE.TER.ENRR
2             COL  2020  55.733109                        0  SE.TER.ENRR
3             COL  2019  56.666302                        0  SE.TER.ENRR
4             COL  2018  57.320541                        0  SE.TER.ENRR

                         indicator.value country.id country.value
0  School enrollment, tertiary (% gross)         CO      Colombia
1  School enrollment, tertiary (% gross)         CO      Colombia
2  School enrollment, tertiary (% gross)         CO      Colombia
3  School enrollment, tertiary (% gross)         CO      Colombia
4  School enrollment, tertiary (% gross)         CO      Colombia

In [32]:
df.head(5)

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,COL,2022,NaN,,,0,SE.TER.ENRR,"School enrollment, tertiary (% gross)",CO,Colombia
1,COL,2021,58.315922,,,0,SE.TER.ENRR,"School enrollment, tertiary (% gross)",CO,Colombia
2,COL,2020,55.733109,,,0,SE.TER.ENRR,"School enrollment, tertiary (% gross)",CO,Colombia
3,COL,2019,56.666302,,,0,SE.TER.ENRR,"School enrollment, tertiary (% gross)",CO,Colombia
4,COL,2018,57.320541,,,0,SE.TER.ENRR,"School enrollment, tertiary (% gross)",CO,Colombia

In [3]:
import requests
import pandas as pd

# Tu clave API de OpenWeatherMap
API_KEY = 'be4936fd03a6f1a860e3d1fa4796d038'
# URL base de la API
BASE_URL = "http://api.openweathermap.org/data/2.5/weather"

# Parámetros de la solicitud: ciudad y unidad de medida (metric para Celsius)
params = {
    'q': 'Madrid,ES',  # Puedes cambiarlo por tu ciudad de interés
    'appid': API_KEY,
    'units': 'metric'
}

# Hacer la solicitud a la API
response = requests.get(BASE_URL, params=params)
data = response.json()

# Verificar si la respuesta contiene los datos esperados
if 'main' in data and 'weather' in data and 'name' in data:
    # Crear un DataFrame a partir de los datos
    weather_data = {
        'city': data['name'],
        'temperature': data['main']['temp'],
        'humidity': data['main']['humidity'],
        'pressure': data['main']['pressure'],
        'description': data['weather'][0]['description'],
    }

    df = pd.DataFrame([weather_data])
    print(df)
else:
    # Imprimir el mensaje de error de la API o un mensaje personalizado
    print("Error al obtener los datos de la API:", data.get('message', 'No se encontraron datos.'))

Error al obtener los datos de la API: Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.

In [8]:
import requests
import pandas as pd

# Tu clave API de Storm Glass
API_KEY = '1d4e5dac-d5dd-11ee-91a9-0242ac130002-1d4e5e38-d5dd-11ee-91a9-0242ac130002'

# URL base de la API de Storm Glass
BASE_URL = "https://api.stormglass.io/v2/weather/point"

# Parámetros para la solicitud
# Coordenadas para Bogotá, Colombia
params = {
    'lat': 4.7110,  # Latitud de Bogotá
    'lng': -74.0721,  # Longitud de Bogotá
    'params': ','.join([
        'airTemperature',  # Temperatura del aire
        'humidity',        # Humedad
        'windSpeed',       # Velocidad del viento
        'cloudCover',      # Cobertura de nubes
        'precipitation'    # Precipitación
    ]),
}

# Encabezados necesarios para la autenticación
headers = {
    'Authorization': API_KEY
}

# Hacer la solicitud a la API
response = requests.get(BASE_URL, params=params, headers=headers)
data = response.json()

# Crear una lista para almacenar los datos de cada hora
weather_data_list = []

if 'hours' in data:
    for hour_data in data['hours']:
        weather_data = {
            'ciudad': 'Bogotá',  # Añadir el nombre de la ciudad
            'time': hour_data['time'],
            'temperature': hour_data['airTemperature']['noaa'],
            'humidity': hour_data['humidity']['noaa'],
            'windSpeed': hour_data['windSpeed']['noaa'],
            'cloudCover': hour_data['cloudCover']['noaa'],
            'precipitation': hour_data['precipitation']['noaa'],
        }
        weather_data_list.append(weather_data)

    # Crear el DataFrame y añadir una columna para el nombre de la ciudad
    df = pd.DataFrame(weather_data_list)
    print(df)
else:
    print("Error al obtener los datos de la API:", data.get('message', 'No se encontraron datos.'))

     ciudad                       time  temperature  humidity  windSpeed  \
0    Bogotá  2024-02-28T00:00:00+00:00        11.92     92.80       1.45
1    Bogotá  2024-02-28T01:00:00+00:00        11.76     93.90       1.37
2    Bogotá  2024-02-28T02:00:00+00:00        11.59     95.00       1.30
3    Bogotá  2024-02-28T03:00:00+00:00        11.42     96.10       1.22
4    Bogotá  2024-02-28T04:00:00+00:00        11.19     96.07       1.13
..      ...                        ...          ...       ...        ...
236  Bogotá  2024-03-08T20:00:00+00:00        11.10     95.43       1.34
237  Bogotá  2024-03-08T21:00:00+00:00        11.14     95.70       1.44
238  Bogotá  2024-03-08T22:00:00+00:00        11.18     95.97       1.53
239  Bogotá  2024-03-08T23:00:00+00:00        11.22     96.23       1.62
240  Bogotá  2024-03-09T00:00:00+00:00        11.26     96.50       1.71

     cloudCover  precipitation
0         70.80           0.07
1         76.07           0.06
2         81.33           0.04
3         86.60           0.03
4         89.93           0.04
..          ...            ...
236       73.53           0.11
237       72.40           0.09
238       71.27           0.07
239       70.13           0.05
240       69.00           0.03

[241 rows x 7 columns]

In [9]:
df.head(10)

,ciudad,time,temperature,humidity,windSpeed,cloudCover,precipitation
0,Bogotá,2024-02-28T00:00:00+00:00,11.92,92.80,1.45,70.80,0.07
1,Bogotá,2024-02-28T01:00:00+00:00,11.76,93.90,1.37,76.07,0.06
2,Bogotá,2024-02-28T02:00:00+00:00,11.59,95.00,1.30,81.33,0.04
3,Bogotá,2024-02-28T03:00:00+00:00,11.42,96.10,1.22,86.60,0.03
4,Bogotá,2024-02-28T04:00:00+00:00,11.19,96.07,1.13,89.93,0.04
5,Bogotá,2024-02-28T05:00:00+00:00,10.97,96.03,1.03,93.27,0.04
6,Bogotá,2024-02-28T06:00:00+00:00,10.74,96.00,0.94,96.60,0.05
7,Bogotá,2024-02-28T07:00:00+00:00,10.47,96.33,0.90,95.03,0.05
8,Bogotá,2024-02-28T08:00:00+00:00,10.20,96.67,0.87,93.47,0.05
9,Bogotá,2024-02-28T09:00:00+00:00,9.93,97.00,0.83,91.90,0.05